version: '3.9'

x-limits:
  medium:
    resources: &limits_medium
      limits:
        cpus: '0.64'
        memory: 128M
      reservations:
        cpus: '0.32'
        memory: 32M
  small:
    resources: &limits_small
      limits:
        cpus: '0.32'
        memory: 64M
      reservations:
        cpus: '0.16'
        memory: 32M

services:

  pdf-sender-bot:
    container_name: pdf-sender-bot
    restart: unless-stopped
    build:
      context: pdf-sender-bot
    networks:
      - backend
    deploy:
      resources: *limits_small

  pdf-sender-web:
    container_name: pdf-sender-bot
    restart: unless-stopped
    build:
      context: pdf-sender-web
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/ca.crt:/etc/nginx/ca.crt:ro
      - ./infra/ca.key:/etc/nginx/ca.key:ro
    ports:
      - "443:443"
    networks:
      - backend
    deploy:
      resources: *limits_small

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:15.2-alpine3.17
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./infra/.env
    networks:
      - backend
    deploy:
      resources: *limits_medium

networks:
  backend:
    name: backend

volumes:
  postgres:
    name: postgres
    driver: local